version: '3.7'
services:

  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: telegraf 
      INFLUXDB_ADMIN_ENABLED: "True" 
      INFLUXDB_ADMIN_USER: admin 
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword 
      INFLUXDB_USER: telegraf 
      INFLUXDB_USER_PASSWORD: telegraf
    networks:
      - monitoring          
      
  telegraf:
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always 
    networks:
      - monitoring

volumes:
  influxdb-volume:

networks:
  monitoring:
