apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deployment
  namespace: default
  labels:
    app:  my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  my-app
    spec:
      containers:
        - name:  nginx
          image:  nginx:1.13
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
