version: '3.1'

networks:
  default:
    external:
      name: prometheus-tier

services:
  vmware_exporter:

    image: pryorda/vmware_exporter:latest
    ports:
        - "9275:9272"
    environment:
        VSPHERE_HOST: "IP"
        VSPHERE_USER: "USERNAME"
        VSPHERE_PASSWORD: "PASSWORD"
        VSPHERE_IGNORE_SSL: "True"
        VSPHERE_COLLECT_VMS: "False"
        VSPHERE_COLLECT_VMGUESTS: "False"
    restart: always

    #FOR DEBUG UNCOMMENT NEXT LINE
    #command: ["-l","DEBUG"]
