# -*- mode: ruby -*-
# vi: set ft=ruby :

# Main idea - https://gist.github.com/roblayton/c629683ca74658412487. Thanks you very much, @roblayton!
infrastructure = {
  "stage" => {
    "mixed" => { :ip => "192.168.30.20", :cpus => 1, :mem => 1024, :os => "debian/buster64" },
  },
  "production" => {
    "loadbalancer" => { :ip => "192.168.40.20", :cpus => 1, :mem => 512, :os => "debian/buster64" },
    "app" => { :ip => "192.168.40.30", :cpus => 1, :mem => 1024, :os => "centos/7" },
    "db" => { :ip => "192.168.40.40", :cpus => 1, :mem => 512, :os => "centos/7" },
  }
}


Vagrant.configure("2") do |config|

  infrastructure.each do |(site, machines)|

    machines.each_with_index do |(hostname, info), index|

      config.vm.define "#{site}.#{hostname}" do |cfg|
        cfg.vm.provider :virtualbox do |vb, override|
          config.vm.box = info[:os]
          
          config.ssh.insert_key = false


          override.vm.network :private_network, ip: "#{info[:ip]}"
          override.vm.hostname = "node-#{site}-#{hostname}"
          vb.name = "#{site}.#{hostname}"
          vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        end # end provider
      
         config.vm.provision "shell", inline: <<-SHELL
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
          systemctl restart sshd.service
          SHELL

      end # end config

      

    end # end machines

  end # end infrastructure
  
end