# -*- mode: ruby -*-
# vi: set ft=ruby :

# Main idea - https://gist.github.com/roblayton/c629683ca74658412487. Thanks you very much, @roblayton!
cluster = {
  "backend" => { :ip => "192.168.30.10", :cpus => 1, :mem => 512 },
  "db" => { :ip => "192.168.30.20", :cpus => 1, :mem => 512 },
  "nginx" => { :ip => "192.168.30.30", :cpus => 1, :mem => 512 },
}


Vagrant.configure("2") do |config|

  cluster.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/bionic64"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end # end provider

      
    end # end config

  end # end cluster
end