- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - virtualenv
    update_cache: yes
    state: latest
- name: Install Python dependencies via pip in a virtualenv
  pip:
    requirements: "{{DEFAULT_APP_DEPLOYMENT_DIR}}/app/requirements.txt"
    virtualenv: "{{DEFAULT_APP_DEPLOYMENT_DIR}}/venv"
