version: "3"
services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    restart: always
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: telegraf 
      INFLUXDB_ADMIN_ENABLED: "True" 
      INFLUXDB_ADMIN_USER: admin 
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword 
      INFLUXDB_USER: telegraf 
      INFLUXDB_USER_PASSWORD: telegraf

  telegraf:
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always 
    networks:
      - monitoring


networks:
  monitoring:

volumes:
  grafana-volume:
  influxdb-volume: