apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        type: web-server
        app: nginx
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          resources:
            limits:
              cpu: 200m
              memory: 100Mi