- name: Start installation procedure on Debian
  import_tasks: debian/install_mongodb.yml
  when: ansible_facts['os_family'] == 'Debian'
- name: Start installation procedure on CentOS
  import_tasks: centos/install_mongodb.yml
  when: ansible_facts['os_family'] == 'RedHat'
