---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    name: myapp
    app: my-app
spec:
  containers:
  - name: nginx
    image: nginx:1.12
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
