apiVersion: v1
kind: Service
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
      name: fluentd-elasticsearch
  ports:
    - nodePort: 30090
      port: 80