---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - while true; do date; echo Hello from the Kubernetes cluster; sleep 1; done
      restartPolicy: Never