Vagrant.configure("2") do |config|

  config.vm.define "linux" do |linux|
    linux.vm.box = "centos/7"
    linux.vm.provision "shell", path: "centos_provision.sh"

    linux.vm.network "private_network", type: "dhcp"
  end

  # config.vm.define "microsoft" do |microsoft|
  #   microsoft.vm.box = "mwrock/Windows2016"
  # end
end
